{{- if .Values.deployment.create }}
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: mysql-kf
  labels:
    component: mysql-kf
{{ include "pipelines.commonLabels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      component: mysql-kf
{{ include "pipelines.commonLabels" . | indent 6 }}
  template:
    metadata:
      labels:
        component: mysql-kf
{{ include "pipelines.commonLabels" . | indent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.db.podSecurityContext | nindent 8 }}
      serviceAccountName: mysql-kf
      volumes:
      - name: mysql-init-scripts
        configMap:
          name: mysql-kf
      - name: mysql-config
        configMap:
          name: mysql-kf
      - name: mysql-kf-secret
        secret:
          secretName: mysql-kf-secret
      - name: mysql-cnf
        emptyDir: {}
      - name: mysql-fuse
{{- if .Values.storage.metadata.volumes.storageOverride }}
{{ toYaml .Values.storage.metadata.volumes.storageOverride | nindent 10 }}
{{- else }}
        flexVolume:
          driver: "v3io/fuse"
          options:
            container: {{ .Values.storage.metadata.containerName }}
            subPath: {{ .Values.storage.metadata.subPath }}
            accessKey: {{ .Values.configurations.credentials.accessKey }}
{{- end }}
      - name: dump-volume
        emptyDir: {}

      initContainers:
      - name: init-mysql-cnf
        image: {{ .Values.images.busybox.repository }}:{{ .Values.images.busybox.tag }}
        imagePullPolicy: IfNotPresent
        command:
          - /bin/sh
          - -c
          - |
            echo "[client]" > /config/mysql.cnf
            echo "user=$(cat /mysql-kf-secret/username)" >> /config/mysql.cnf
            echo "password=$(cat /mysql-kf-secret/password)" >> /config/mysql.cnf
            echo "host=mysql-kf" >> /config/mysql.cnf
        volumeMounts:
          - name: mysql-kf-secret
            mountPath: /mysql-kf-secret
            readOnly: true
          - name: mysql-cnf
            mountPath: /config

      - name: dump-old-mysql
        image: mysql:5.6
        imagePullPolicy: IfNotPresent
        command:
          - /bin/bash
          - /etc/config/mysql/init-scripts/dump-or-skip.sh
        env:
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: mysql-kf-secret
                key: username
          - name: MYSQL_PWD
            valueFrom:
              secretKeyRef:
                name: mysql-kf-secret
                key: password
        volumeMounts:
          - name: mysql-fuse
            mountPath: "/var/lib/mysql"
          - name: mysql-init-scripts
            mountPath: /etc/config/mysql/init-scripts
          - name: dump-volume
            mountPath: /dump
          - name: mysql-cnf
            mountPath: /mysql.cnf
            subPath: mysql.cnf
            readOnly: true

      - name: import-into-new-mysql
        image: {{ .Values.images.mysql.repository }}:{{ .Values.images.mysql.tag }}
        imagePullPolicy: {{ .Values.images.imagePullPolicy }}
        command:
          - /bin/bash
          - /etc/config/mysql/init-scripts/import-if-dump-done.sh
        env:
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: mysql-kf-secret
                key: username
          - name: MYSQL_PWD
            valueFrom:
              secretKeyRef:
                name: mysql-kf-secret
                key: password
        volumeMounts:
          - name: mysql-fuse
            mountPath: "/var/lib/mysql"
          - name: mysql-init-scripts
            mountPath: /etc/config/mysql/init-scripts
          - name: dump-volume
            mountPath: /dump
          - name: mysql-cnf
            mountPath: /mysql.cnf
            subPath: mysql.cnf
            readOnly: true

      containers:
      - name: {{ .Values.configurations.mysql.spec.template.spec.containers.name }}
        securityContext:
{{ toYaml .Values.db.securityContext | indent 14 }}
        image: {{ .Values.images.mysql.repository }}:{{ .Values.images.mysql.tag }}
        imagePullPolicy: {{ .Values.images.imagePullPolicy }}
        command: [ "/bin/bash", "/etc/config/mysql/start-mysql.sh" ]
        ports:
          - name: mysql-kf
            containerPort: 3306
            protocol: TCP
        livenessProbe:
          exec:
            command: ["mysqladmin","--defaults-extra-file=/mysql.cnf","ping","-h","127.0.0.1"]
          initialDelaySeconds: {{ .Values.configurations.mysql.spec.template.spec.containers.livenessProbe.initialDelaySeconds }}
          failureThreshold: {{ .Values.configurations.mysql.spec.template.spec.containers.livenessProbe.failureThreshold }}
          periodSeconds: {{ .Values.configurations.mysql.spec.template.spec.containers.livenessProbe.periodSeconds }}
        readinessProbe:
          exec:
            command: ["mysqladmin","--defaults-extra-file=/mysql.cnf","ping","-h","127.0.0.1"]
          initialDelaySeconds: {{ .Values.configurations.mysql.spec.template.spec.containers.readinessProbe.initialDelaySeconds }}
          failureThreshold: {{ .Values.configurations.mysql.spec.template.spec.containers.readinessProbe.failureThreshold }}
          periodSeconds: {{ .Values.configurations.mysql.spec.template.spec.containers.readinessProbe.periodSeconds }}
        env:
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: mysql-kf-secret
                key: username
          - name: MYSQL_PWD
            valueFrom:
              secretKeyRef:
                name: mysql-kf-secret
                key: password
        volumeMounts:
          - name: mysql-fuse
            mountPath: "/var/lib/mysql"
          - name: mysql-config
            mountPath: /etc/config/mysql
          - name: mysql-init-scripts
            mountPath: /etc/config/mysql/init-scripts
          - name: mysql-cnf
            mountPath: /mysql.cnf
            subPath: mysql.cnf
        resources:
{{ toYaml .Values.resources.mysql | indent 14 }}
{{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
{{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName | quote }}
{{- end }}
{{- end }}
