{{- if .Values.deployment.create }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-pipeline-persistenceagent
  namespace: {{ .Release.Namespace }}
  labels:
    component: ml-pipeline-persistenceagent
{{ include "pipelines.commonLabels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      component: ml-pipeline-persistenceagent
{{ include "pipelines.commonLabels" . | indent 6 }}
  template:
    metadata:
      labels:
        component: ml-pipeline-persistenceagent
{{ include "pipelines.commonLabels" . | indent 8 }}
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
    spec:
      containers:
      - name: ml-pipeline-persistenceagent
        image: {{ .Values.images.persistenceagent.repository }}:{{ .Values.images.persistenceagent.tag }}
        imagePullPolicy: {{ .Values.images.imagePullPolicy }}
        env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: TTL_SECONDS_AFTER_WORKFLOW_FINISH
            value: {{ .Values.configurations.persistenceagent.ttlSecondsAfterWorkflowFinish | quote }}
          - name: NUM_WORKERS
            value: {{ .Values.configurations.persistenceagent.numWorkers | quote }}
          - name: LOG_LEVEL
            value: "info"
        {{- if .Values.resources.persistenceAgent }}
        resources:
{{ toYaml .Values.resources.persistenceAgent | nindent 10 }}
        {{- end }}
        volumeMounts:
          - mountPath: /var/run/secrets/kubeflow/tokens
            name: persistenceagent-sa-token
        securityContext:
          {{- toYaml .Values.securityContext.defaultContainer | nindent 10 }}
      serviceAccountName: ml-pipeline-persistenceagent
      volumes:
        - name: persistenceagent-sa-token
          projected:
            sources:
              - serviceAccountToken:
                  path: persistenceagent-sa-token
                  expirationSeconds: 3600
                  audience: pipelines.kubeflow.org
{{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
{{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName | quote }}
{{- end }}
{{- end }}
