{{- if .Values.deployment.create }}
{{/* Only create if db existing name was not provided */}}
{{- if not .Values.db.existingSecretName }}

{{- $password := randAlphaNum 16 }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pipelines.dbSecretName" . }}
type: Opaque
stringData:
  username: "kubeflow"
  password: "{{ $password }}"
  mysql.cnf: |
    [client]
    user=kubeflow
    password={{ $password }}
{{- end }}
{{- end }}
