{{- $password := randAlphaNum 16 }}
apiVersion: v1
kind: Secret
metadata:
  name: mysql-kf-secret
type: Opaque
stringData:
  username: "kubeflow"
  password: "{{ $password }}"
  mysql.cnf: |
    [client]
    user=kubeflow
    password={{ $password }}
