apiVersion: v1
appVersion: ">=2.4.1"
version: 0.11.5
name: pipelines-v2
description: Kubeflow pipelines framework for machine learning
home: https://www.kubeflow.org/
icon: https://github.com/kubeflow/marketing-materials/blob/master/logos/Raster/Kubeflow-Logo-RGB.png
sources:
  - https://github.com/kubeflow/pipelines
maintainers:
  - name: Tomer Shor
    email: tomers@iguazio.com
  - name: Adam Melnick
    email: adamm@iguazio.com
  - name: Adam Delman
    email: adamd@iguazio.com
