apiVersion: v1
appVersion: ">=2.16.0"
version: 0.13.5
name: pipelines-v2
description: Kubeflow pipelines framework for machine learning
home: https://www.kubeflow.org/
icon: https://github.com/kubeflow/marketing-materials/blob/master/logos/Raster/Kubeflow-Logo-RGB.png
sources:
  - https://github.com/kubeflow/pipelines
maintainers:
  - name: Iguazio
    url: https://www.iguazio.com/
