{{- if eq .Values.storageMode.kind "minio" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: pipeline-install-config
  labels: {}
data:
  minioServiceHost: "{{ tpl .Values.storageMode.minio.serviceHost . }}"
  minioServicePort: "{{ .Values.storageMode.minio.servicePort }}"
  minioDefaultBucket: "{{ .Values.storageMode.minio.defaultBucket }}"
{{- end -}}
