{{- if .Values.rbac.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: mysql-kf
  labels:
    component: mysql-kf
{{ include "pipelines.commonLabels" . | indent 4 }}
data:
  health_check.sh: |
    mysqladmin status --user=${DB_USER} --password=${MYSQL_PWD} --host=127.0.0.1

  upgrade_mysql_8.0.26.sh: |
    #!/usr/bin/env bash
    set -euo pipefail

    readonly INIT_SCRIPT="/etc/config/mysql/init-scripts/create_user.sql"
    readonly LOCK_FILE="/var/lib/mysql/.lock_upgrade_mysql_8.0.26"
    readonly DUMP_FILE="/tmp/pre_upgrade_dump.sql"
    readonly LOG_FILE="/tmp/mysql_log"

    if [[ -f "${LOCK_FILE}" ]]; then
      echo "MySQL has already been initialized. Skipping..."
      exit 0
    fi

    if [[ -d "/var/lib/mysql" ]]; then
      echo "Cleaning up conflicting files..."
      rm -f /var/lib/mysql/ib_logfile* || echo "No old redo log files found"
      rm -rf /var/lib/mysql/sys || echo "/var/log/mysql/sys does not exist"
      rm -rf /var/lib/mysql/mysql/innodb_table_stats.ibd || echo "/var/log/mysql/mysql/innodb_table_stats.ibd does not exist"
      echo "Starting old MySQL instance for data dump (using innodb_force_recovery=1)..."
      mysqld --log-error-verbosity=3 --skip-grant-tables --innodb_force_recovery=1 --log-error="${LOG_FILE}" &>> "${LOG_FILE}" &
      PID=$!

      echo "Waiting for MySQL to start..."
      while true; do
        if ! kill -0 "${PID}" 2>/dev/null; then
          echo "MySQL process (PID ${PID}) is no longer running. Check ${LOG_FILE}.* for errors."
          exit 1
        fi

        if mysqladmin ping --silent 2>/dev/null; then
          echo "MySQL started successfully."
          break
        fi

        sleep 1
        cat "${LOG_FILE}.*" 2>/dev/null || true
      done

      echo "Dumping existing data to ${DUMP_FILE}..."
      mysqldump -u "${DB_USER}" --all-databases > "${DUMP_FILE}" || echo "Failed to dump existing data" && cat "${LOG_FILE}".* 2>/dev/null

      echo "Shutting down old MySQL..."
      mysqladmin shutdown
      wait "${PID}"

      echo "Existing data dumped to ${DUMP_FILE}"
    else
      echo "No existing MySQL directory found. Initializing new MySQL data directory..."
      mysqld --initialize --log-error="${LOG_FILE}" --skip-grant-tables --init-file="${INIT_SCRIPT}" &>> "${LOG_FILE}"
    fi

    echo "Starting new MySQL instance..."
    mysqld --datadir="/var/lib/mysql" --log-error="${LOG_FILE}" --skip-grant-tables --init-file="${INIT_SCRIPT}" &>> "${LOG_FILE}" &
    NEW_PID=$!

    echo "Waiting for the new MySQL instance to start..."
    until mysqladmin ping --silent 2>/dev/null; do
      sleep 1
    done

    if [[ -f "${DUMP_FILE}" ]]; then
      echo "Importing old data from ${DUMP_FILE}..."
      mysql -u "${DB_USER}" < "${DUMP_FILE}"
    fi

    mysqladmin shutdown
    wait "${NEW_PID}"

    touch "${LOCK_FILE}"
    echo "MySQL has been re-initialized and existing data (if any) has been imported."
    rm -f "${LOG_FILE}" || true

  start-mysql.sh: |
    #!/usr/bin/env bash
    set -euo pipefail

    echo "Starting MySQL ..."
    mysqld \
      --default-authentication-plugin=mysql_native_password \
      --disable-log-bin \
{{- end }}
