{{- if .Values.rbac.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: mysql-kf
  labels:
    component: mysql-kf
{{ include "pipelines.commonLabels" . | indent 4 }}
data:
  health_check.sh: |
    mysqladmin status

  init-mysql.sh: |
    #!/usr/bin/env bash
    set -euo pipefail

    readonly INIT_SCRIPT="/etc/config/mysql/init-scripts/create_user.sql"
    readonly LOCK_FILE="/var/lib/mysql/.init_mysql_8.0.26"

    if [[ -f "${LOCK_FILE}" ]]; then
      echo "MySQL has already been initialized. Skipping..."
      exit 0
    fi

    if [[ -d "/var/lib/mysql" ]]; then
      echo "Cleaning up conflicting files..."
      rm -f /var/lib/mysql/ib_logfile* || echo "No old redo log files found"
      rm -rf /var/lib/mysql/sys || echo "/var/log/mysql/sys does not exist"
      rm -rf /var/lib/mysql/mysql/innodb_table_stats.ibd || echo "/var/log/mysql/mysql/innodb_table_stats.ibd does not exist"
    fi

    touch "${LOCK_FILE}"

  start-mysql.sh: |
    #!/usr/bin/env bash
    set -euo pipefail

    readonly INIT_SCRIPT="/etc/config/mysql/init-scripts/create_user.sql"

    echo "Starting MySQL ..."
    mysqld \
      --default-authentication-plugin=mysql_native_password \
      --disable-log-bin \
      --init-file="${INIT_SCRIPT}"
{{- end }}
