{{- if .Values.rbac.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: mysql-init-scripts
  labels:
    component: mysql-kf
{{ include "pipelines.commonLabels" . | indent 4 }}
data:
  create_user.sql: |
    CREATE USER IF NOT EXISTS '${DB_USER}'@'%' IDENTIFIED BY '${MYSQL_PWD}';
    GRANT ALL PRIVILEGES ON *.* TO '${DB_USER}'@'%';
    FLUSH PRIVILEGES;
{{- end }}
