{{- if .Values.deployment.create }}
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: mysql-kf
  labels:
    component: mysql-kf
{{ include "pipelines.commonLabels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      component: mysql-kf
{{ include "pipelines.commonLabels" . | indent 6 }}
  template:
    metadata:
      labels:
        component: mysql-kf
{{ include "pipelines.commonLabels" . | indent 8 }}
    spec:
      serviceAccountName: mysql-kf

      securityContext:
        {{- toYaml .Values.db.podSecurityContext | nindent 8 }}
      serviceAccountName: mysql-kf
      volumes:
        - name: mysql-init-scripts
          configMap:
            name: mysql-init-scripts
        - name: mysql-config
          configMap:
            name: mysql-kf
        # Add MySQL data mount (Fuse)
        - name: mysql-fuse
{{- if .Values.storage.metadata.volumes.storageOverride }}
{{ toYaml .Values.storage.metadata.volumes.storageOverride | nindent 10 }}
{{- else }}
          flexVolume:
            driver: "v3io/fuse"
            options:
              container: {{ .Values.storage.metadata.containerName }}
              subPath: {{ .Values.storage.metadata.subPath }}
              accessKey: {{ .Values.configurations.credentials.accessKey }}
{{- end }}
      initContainers:
        - name: init
          image: {{ .Values.images.mysql.repository }}:{{ .Values.images.mysql.tag }}
          imagePullPolicy: {{ .Values.images.imagePullPolicy }}
          resources:
{{ toYaml .Values.resources.mysql | indent 12 }}
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-kf-secret
                  key: username
            - name: MYSQL_PWD
              valueFrom:
                secretKeyRef:
                  name: mysql-kf-secret
                  key: password

          command: [ "/bin/bash", "/etc/config/mysql/upgrade_mysql_8.0.26.sh" ]
          securityContext:
{{ toYaml .Values.db.securityContext | indent 14 }}
          volumeMounts:
            - name: mysql-fuse
              mountPath: "/var/lib/mysql"
            - name: mysql-config
              mountPath: /etc/config/mysql
            - name: mysql-init-scripts
              mountPath: /etc/config/mysql/init-scripts
      containers:
        - name: {{ .Values.configurations.mysql.spec.template.spec.containers.name }}
          securityContext:
{{ toYaml .Values.db.securityContext | indent 14 }}
          image: {{ .Values.images.mysql.repository }}:{{ .Values.images.mysql.tag }}
          imagePullPolicy: {{ .Values.images.imagePullPolicy }}
          command: [ "/bin/bash", "/etc/config/mysql/start-mysql.sh" ]
          ports:
            - name: mysql-kf
              containerPort: 3306
              protocol: TCP
          livenessProbe:
            exec:
              command: [ "/bin/bash", "/etc/config/mysql/health_check.sh" ]
            initialDelaySeconds: {{ .Values.configurations.mysql.spec.template.spec.containers.livenessProbe.initialDelaySeconds }}
            failureThreshold: {{ .Values.configurations.mysql.spec.template.spec.containers.livenessProbe.failureThreshold }}
            periodSeconds: {{ .Values.configurations.mysql.spec.template.spec.containers.livenessProbe.periodSeconds }}
          readinessProbe:
            exec:
              command: [ "/bin/bash", "/etc/config/mysql/health_check.sh" ]
            initialDelaySeconds: {{ .Values.configurations.mysql.spec.template.spec.containers.readinessProbe.initialDelaySeconds }}
            failureThreshold: {{ .Values.configurations.mysql.spec.template.spec.containers.readinessProbe.failureThreshold }}
            periodSeconds: {{ .Values.configurations.mysql.spec.template.spec.containers.readinessProbe.periodSeconds }}
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-kf-secret
                  key: username
            - name: MYSQL_PWD
              valueFrom:
                secretKeyRef:
                  name: mysql-kf-secret
                  key: password
          volumeMounts:
            - name: mysql-fuse
              mountPath: "/var/lib/mysql"
            - name: mysql-config
              mountPath: /etc/config/mysql
            - name: mysql-init-scripts
              mountPath: /etc/config/mysql/init-scripts
          resources:
{{ toYaml .Values.resources.mysql | indent 14 }}
{{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
{{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName | quote }}
{{- end }}
{{- end }}
