apiVersion: v1
kind: Secret
metadata:
  name: mysql-kf-secret
  annotations:
    "helm.sh/resourcePolicy": "keep"

type: Opaque
data:
  username: {{ randAlpha 10 | b64enc | quote }}
  password: {{ randAlphaNum 16 | b64enc | quote }}
