apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.keycloak.extraEnvVarsCM }}
  labels:
    {{ include "v3io-keycloak.labels" . | nindent 4 }}
data:
  # Args for keycloak to import realms from the mounted realms.json file
  KEYCLOAK_EXTRA_ARGS: "-Dkeycloak.migration.action=import -Dkeycloak.migration.provider=singleFile -Dkeycloak.migration.strategy=IGNORE_EXISTING -Dkeycloak.migration.file=/realm_config/realms.json"

  # mysql db configuration
  KC_DB: "mysql"
  KEYCLOAK_DATABASE_HOST: "{{ .Values.keycloak.externalDatabase.host }}"
  KEYCLOAK_DATABASE_PORT: "{{ .Values.keycloak.externalDatabase.port }}"
  KC_DB_URL: "jdbc:mysql://{{ .Values.keycloak.externalDatabase.host }}:{{ .Values.keycloak.externalDatabase.port }}/{{ .Values.keycloak.externalDatabase.database }}"

  # ingress proxy settings
  # pass the X-Forwarded-* headers to Keycloak, so it can generate correct URLs
  KC_PROXY_HEADERS: "xforwarded"
  # enable http scheme when behind a TLS terminating proxy
  KC_HTTP_ENABLED: "true"
  # don't enforce strict hostname check (since we use different hostnames per tenant)
  KC_HOSTNAME_STRICT: "false"
