{{- if .Values.rbac.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
  labels:
    component: workflow-controller
{{ include "pipelines.commonLabels" . | indent 4 }}
{{- if eq .Values.storageMode.kind "minio" }}
data:
  metricsConfig: |
    enabled: false
    path: /metrics
    port: 9090
    ignoreErrors: false

  # https://github.com/argoproj/argo-workflows/blob/v3.7.7/docs/workflow-controller-configmap.yaml
  artifactRepository: |
    archiveLogs: {{ if hasKey .Values.storageMode "archiveLogs" }}{{ .Values.storageMode.archiveLogs }}{{ else }}true{{ end }}
    s3:
      endpoint: {{ .Values.storageMode.minio.serviceHost }}:{{ .Values.storageMode.minio.servicePort }}
      bucket: {{ .Values.storageMode.minio.defaultBucket }}
      keyPrefix: {{ .Values.storageMode.minio.keyPrefix }}
      insecure: {{ .Values.storageMode.minio.insecure }}
      accessKeySecret:
        name: {{ include "pipelines.minioStorageSecretName" . }}
        key: {{ include "pipelines.minioAccessKeyName" . }}
      secretKeySecret:
        name: {{ include "pipelines.minioStorageSecretName" . }}
        key: {{ include "pipelines.minioSecretKeyName" . }}

  executor: |
    imagePullPolicy: IfNotPresent
    securityContext:
{{ toYaml .Values.securityContext.workflowController.executor | indent 6 }}

{{- else if eq .Values.storageMode.kind "v3io" }}
data:
  config: |
    {
      namespace: {{ .Release.Namespace }},
      artifactRepository:
      {
          s3: {
              bucket: {{ .Values.storage.artifacts.containerName }},
              keyPrefix: mlpipeline,
              endpoint: v3io-webapi.{{ .Release.Namespace }}:{{ .Values.configurations.ports.nginxPort }},
              insecure: {{ .Values.storageMode.minio.insecure }},
              accessKeySecret: {
                  name: v3io-webapi-secret,
                  key: accesskey
              },
              secretKeySecret: {
                  name: v3io-webapi-secret,
                  key: secretkey
              }
          },
          archiveLogs: {{ if hasKey .Values.storageMode "archiveLogs" }}{{ .Values.storageMode.archiveLogs }}{{ else }}true{{ end }}
      }
    }
  executor: |
    imagePullPolicy: IfNotPresent
    securityContext:
{{ toYaml .Values.securityContext.workflowController.executor | indent 6 }}
{{- end }}
{{- end }}
