apiVersion: v2
name: spark-operator
description: A Helm chart for Spark on Kubernetes operator.
version: 2.0.21
appVersion: 2.2.1
keywords:
- apache spark
- big data
home: https://github.com/kubeflow/spark-operator
maintainers:
- name: Gal Topper
