{{- if .Values.deployment.create }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata-grpc-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    component: metadata-grpc-server
{{ include "pipelines.commonLabels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: metadata-grpc-server
{{ include "pipelines.commonLabels" . | indent 6 }}
  template:
    metadata:
      labels:
        component: metadata-grpc-server
{{ include "pipelines.commonLabels" . | indent 8 }}
    spec:
      initContainers:
        - name: metadata-init
          env:
            - name: DBCONFIG_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-kf-secret
                  key: username
            - name: MYSQL_PWD
              valueFrom:
                secretKeyRef:
                  name: mysql-kf-secret
                  key: password
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: metadata-mysql-configmap
                  key: MYSQL_DATABASE
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: metadata-mysql-configmap
                  key: MYSQL_HOST
            - name: MYSQL_PORT
              valueFrom:
                configMapKeyRef:
                  name: metadata-mysql-configmap
                  key: MYSQL_PORT
          command: [
            'mysqladmin',
            'status',
            '--user=$(DBCONFIG_USER)',
            '--host=$(MYSQL_HOST)',
            '--port=$(MYSQL_PORT)',
            '--wait=10'
          ]
          image: {{ .Values.images.metadata.init.repository }}:{{ .Values.images.metadata.init.tag }}
          securityContext:
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 0
            capabilities:
              drop:
                - ALL
          imagePullPolicy: {{ .Values.images.imagePullPolicy }}
      containers:
        - name: metadata-container
          image: {{ .Values.images.metadata.container.repository }}:{{ .Values.images.metadata.container.tag }}
          imagePullPolicy: {{ .Values.images.imagePullPolicy }}
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: metadata-mysql-configmap
                  key: MYSQL_DATABASE
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: metadata-mysql-configmap
                  key: MYSQL_HOST
            - name: MYSQL_PORT
              valueFrom:
                configMapKeyRef:
                  name: metadata-mysql-configmap
                  key: MYSQL_PORT

            - name: DBCONFIG_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-kf-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-kf-secret
                  key: password

          command: [ "/bin/metadata_store_server" ]
          args: [ "--grpc_port=8080",
                  "--mysql_config_database=$(MYSQL_DATABASE)",
                  "--mysql_config_host=$(MYSQL_HOST)",
                  "--mysql_config_password=$(DB_PASSWORD)",
                  "--mysql_config_user=$(DBCONFIG_USER)",
                  "--enable_database_upgrade=true"
          ]
          ports:
            - name: grpc-api
              containerPort: 8080
          livenessProbe:
            tcpSocket:
              port: grpc-api
            initialDelaySeconds: 3
            periodSeconds: 5
            timeoutSeconds: 2
          readinessProbe:
            tcpSocket:
              port: grpc-api
            initialDelaySeconds: 3
            periodSeconds: 5
            timeoutSeconds: 2
      serviceAccountName: metadata-grpc-server
{{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
{{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName | quote }}
{{- end }}
{{- end }}
